version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0
    container_name: service-elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      #- cluster.initial_master_nodes=elasticsearch
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
#    mem_limit: 500m
#    cap_add:
#      - IPC_LOCK
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data:rw

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0
    container_name: service-kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkinService
    ports:
      - 9411:9411

  logstash:
    image: docker.elastic.co/logstash/logstash:7.8.0
    container_name: service-logstash
    restart: unless-stopped
    command: logstash -f /usr/share/logstash/pipeline
    volumes:
      - ./Logstash/config:/usr/share/logstash/config:ro
      - ./Logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "12204:12204"
    depends_on:
      - elasticsearch

  discovery:
    image: dzmdre/service-discovery
    container_name: discovery
    build:
      context: ./ServiceDiscovery
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    depends_on:
      - logstash
    links:
      - logstash

  gateway:
    image: dzmdre/api-gateway
    container_name: api-gateway
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    links:
      - discovery
      - logstash
      - zipkin

  products:
    image: dzmdre/service-products
    container_name: products
    build:
      context: ./ProductService
      dockerfile: Dockerfile
    ports:
      - "7501:2222"
    depends_on:
      - discovery
    links:
      - discovery
      - logstash
      - zipkin

  orders:
    image: dzmdre/orders-service
    container_name: orders-service
    build:
      context: ./OrdersService
      dockerfile: Dockerfile
    ports:
      - "7502:2222"
    depends_on:
      - discovery
    links:
      - discovery
      - logstash
      - zipkin

  payments:
    image: dzmdre/payments-service
    container_name: payments-service
    build:
      context: ./PaymentsService
      dockerfile: Dockerfile
    ports:
      - "7503:2222"
    depends_on:
      - discovery
    links:
      - discovery
      - logstash
      - zipkin

  users:
    image: dzmdre/users-service
    container_name: users-service
    build:
      context: ./UsersService
      dockerfile: Dockerfile
    ports:
      - "7504:2222"
    depends_on:
      - discovery
    links:
      - discovery
      - logstash
      - zipkin

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./Prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    links:
      - discovery
      - gateway
      - accounts
      - products
      - orders
      - main

  axonserver:
    image: axoniq/axonserver:latest
    container_name: axonserver
    ports:
      - 8024:8024
      - 8124:8124
      - 8224:8224
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./AxonService/data:/axonserver/data:rw
      - ./AxonService/log:/axonserver/log:rw

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    user: "104"
